use dearhere;

-- MySQL Script generated by MySQL Workbench
-- Thu Dec 10 20:42:41 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dearhere
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dearhere
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dearhere` DEFAULT CHARACTER SET utf8 ;
USE `dearhere` ;

-- -----------------------------------------------------
-- Table `dearhere`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dearhere`.`place` (
  `id` INT unsigned NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dearhere`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dearhere`.`post` (
  `id` INT unsigned NOT NULL AUTO_INCREMENT,
  `dear` VARCHAR(25) NOT NULL,
  `createdtime` TIMESTAMP NOT NULL,
  `content` TEXT NOT NULL,
  `imageurl` VARCHAR(255) NULL,
  `likes` INT unsigned NULL COMMENT 'UNSIGNED\n',
  `place_id` INT unsigned NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_place_idx` (`place_id` ASC),
  INDEX `dear_index` (`dear` ASC),
  CONSTRAINT `fk_post_place`
    FOREIGN KEY (`place_id`)
    REFERENCES `dearhere`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dearhere`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dearhere`.`reply` (
  `id` INT unsigned NOT NULL AUTO_INCREMENT,
  `createdtime` TIMESTAMP NOT NULL,
  `content` TEXT NOT NULL,
  `likes` INT unsigned NULL,
  `post_id` INT unsigned NOT NULL,
  PRIMARY KEY (`id`, `post_id`),
  INDEX `fk_reply_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_reply_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `dearhere`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

show tables;
select * from post;
select * from reply;
select * from place;

insert into place (name) values ('test');
insert into post (dear,content,place_id) 
values ('toitoi','깃토이, 뷰티토이, 플토이,소토이',1);
insert into post (dear,content,place_id) 
values ('toitoi','윙가르디움 레비오우사',1);
insert into post (dear,content,place_id) 
values ('toitoi','해리포터',1);
insert into post (dear,content,place_id) 
values ('깃토이','깃 마스터 짱짱',1);
insert into post (dear,content,place_id) 
values ('깃토이','프론트 대장님',1);
insert into post (dear,content,place_id) 
values ('뷰티토이','욕심토이 ios toi',1);
insert into post (dear,content,place_id) 
values ('뷰티토이','해외에서 한국인 혹은 한국과 조금이라도  관련된 일을 하게 된다면 반갑지 않은 일을 만나게 된다. 
번역가나 통역가가 아닌데 (실상은 내 생존에 필요한 현지 외국어도 힘든데ㅠㅠ) 한국인이기 때문에 현지어(또는 영어)로 번역이나 통역할 일이 생긴다. 
나의 경우 내가 일하던 회사에서 몇 백명의 사원 중 아시아인이 나 혼자였고, 
사무실 안에서 일할 때 한국어를 쓸 일이 한국회사에  전화할 때 말고는 없었다. 
한국인 클라이언트들의 한국어 공격만 아니면 현지에서 일하는 데는 영어를 잘하고 독일어를 조금 하면 문제가 없는 행복한 조건이었다.',1);

insert into reply (content,post_id)
values ('깃토이가 누구에요?',1);

insert into reply (content,post_id)
values ('해리포터 팬이신듯',2);

insert into reply (content,post_id)
values ('난 론할래',3);
